services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            -   mysql

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel
        depends_on:
             app:
                 condition: service_started

    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: base_api
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./docker/certbot/www:/var/www/certbot
            - ./docker/certbot/conf:/etc/letsencrypt
        entrypoint: >
            sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
