name: test-containers-build.yml
on:
  push:
    branches:
      [main, develop]

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Start docker containers
        uses: hoverkraft-tech/compose-action@v2.3.0
        with:
          compose-file: './docker-compose.yml'

      - name: Atraso de 1 minuto para a execução do startup.sh
        run: sleep 60s

      - name: Curl into nginx server
        run: |
          curl -X GET -G -H "Accept: application/json" http://localhost:8000


