name: test-containers-build.yml
on:
  push:
    branches:
      [main, develop]

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Ajusta permissões do projeto
        run: sudo chown -R 1000:1000 .

      - name: Ajusta permissão de execução do startup.sh
        run: |
          sudo chmod +x startup.sh

      - name: Inicia containers do docker compose
        run: |
          docker compose up -d

      - name: Executa startup.sh no container da aplicação
        run: |
          docker compose exec app composer install --no-dev

      - name: Verifica status dos containers
        run: |
          docker compose ps

      - name: Executa startup.sh no container da aplicação
        run: |
          docker compose exec app ./startup.sh


      - name: Requisição para localhost:8000 para verificar estado da aplicação
        run: |
          curl -X GET -G -H "Accept: application/json" http://localhost:8000


